//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotCaptureV2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotCaptureV2.Resources.localization", typeof(localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy_button {
            get {
                return ResourceManager.GetString("copy.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Text.
        /// </summary>
        internal static string copy_text_button {
            get {
                return ResourceManager.GetString("copy.text.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text was found, please select the area again..
        /// </summary>
        internal static string error_text_notfound {
            get {
                return ResourceManager.GetString("error.text.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit_strip_menu {
            get {
                return ResourceManager.GetString("exit.strip.menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string language_panel_cancel {
            get {
                return ResourceManager.GetString("language.panel.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string language_panel_ok {
            get {
                return ResourceManager.GetString("language.panel.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save_button {
            get {
                return ResourceManager.GetString("save.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string settings_apply {
            get {
                return ResourceManager.GetString("settings.apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string settings_backgroundColor_label {
            get {
                return ResourceManager.GetString("settings.backgroundColor.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset/Cancel.
        /// </summary>
        internal static string settings_cancel {
            get {
                return ResourceManager.GetString("settings.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Button.
        /// </summary>
        internal static string settings_dummy {
            get {
                return ResourceManager.GetString("settings.dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover Color.
        /// </summary>
        internal static string settings_hoverColor_label {
            get {
                return ResourceManager.GetString("settings.hoverColor.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        internal static string settings_language_label {
            get {
                return ResourceManager.GetString("settings.language.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_strip_menu {
            get {
                return ResourceManager.GetString("settings.strip.menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string settings_textColor_label {
            get {
                return ResourceManager.GetString("settings.textColor.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Speech.
        /// </summary>
        internal static string text_to_speech_button {
            get {
                return ResourceManager.GetString("text.to.speech.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string translate_button {
            get {
                return ResourceManager.GetString("translate.button", resourceCulture);
            }
        }
    }
}
